/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WebInput {
    'text': string;
  }
}

declare global {


  interface HTMLWebInputElement extends Components.WebInput, HTMLStencilElement {}
  var HTMLWebInputElement: {
    prototype: HTMLWebInputElement;
    new (): HTMLWebInputElement;
  };
  interface HTMLElementTagNameMap {
    'web-input': HTMLWebInputElement;
  }
}

declare namespace LocalJSX {
  interface WebInput extends JSXBase.HTMLAttributes<HTMLWebInputElement> {
    'onClickedItem'?: (event: CustomEvent<any>) => void;
    'text'?: string;
  }

  interface IntrinsicElements {
    'web-input': WebInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


